name: Hello

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "hello everyone"

      - name: Say hello to username
        run: echo "Hello Uttam"
