name: python-lint
on:
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: install requirement 
        run: pip install -r requirement.txt
      - name: run the linter 
        run: flake8 app.py
